from ../libavutil/version import AV_VERSION_INT, AV_VERSION
from ../libavutil/macros import AV_STRINGIFY

const
  LIBSWSCALE_VERSION_MAJOR* = 6
  LIBSWSCALE_VERSION_MINOR* = 4
  LIBSWSCALE_VERSION_MICRO* = 100
  LIBSWSCALE_VERSION_INT* = AV_VERSION_INT(LIBSWSCALE_VERSION_MAJOR, LIBSWSCALE_VERSION_MINOR, LIBSWSCALE_VERSION_MICRO)
  LIBSWSCALE_VERSION* = AV_VERSION(LIBSWSCALE_VERSION_MAJOR, LIBSWSCALE_VERSION_MINOR, LIBSWSCALE_VERSION_MICRO)
  LIBSWSCALE_BUILD* = LIBSWSCALE_VERSION_INT
  LIBSWSCALE_IDENT* = "SwS" & AV_STRINGIFY(LIBSWSCALE_VERSION)
