from ../libavutil/version import AV_VERSION_INT, AV_VERSION

when defined(windows):
  {.push importc, dynlib: "avcodec(|-58|-59|-60|-61|-62).dll", cdecl.}
elif defined(macosx):
  {.push importc, dynlib: "libavcodec(|-58|-59|-60|-61|-62).dylib", cdecl.}
else:
  {.push importc, dynlib: "libavcodec.so(|-58|-59|-60|-61|-62)", cdecl.}

const
  LIBAVCODEC_VERSION_MAJOR* = 59
  LIBAVCODEC_VERSION_MINOR* = 18
  LIBAVCODEC_VERSION_MICRO* = 100
  LIBAVCODEC_VERSION_INT* = AV_VERSION_INT(LIBAVCODEC_VERSION_MAJOR, LIBAVCODEC_VERSION_MINOR, LIBAVCODEC_VERSION_MICRO)
  LIBAVCODEC_VERSION* = AV_VERSION(LIBAVCODEC_VERSION_MAJOR, LIBAVCODEC_VERSION_MINOR, LIBAVCODEC_VERSION_MICRO)
  LIBAVCODEC_BUILD* = LIBAVCODEC_VERSION_INT
  LIBAVCODEC_IDENT* = "Lavc"
  FF_API_OPENH264_SLICE_MODE* = LIBAVCODEC_VERSION_MAJOR < 60
  FF_API_OPENH264_CABAC* = LIBAVCODEC_VERSION_MAJOR < 60
  FF_API_UNUSED_CODEC_CAPS* = LIBAVCODEC_VERSION_MAJOR < 60
  FF_API_THREAD_SAFE_CALLBACKS* = LIBAVCODEC_VERSION_MAJOR < 60
  FF_API_DEBUG_MV* = LIBAVCODEC_VERSION_MAJOR < 60
  FF_API_GET_FRAME_CLASS* = LIBAVCODEC_VERSION_MAJOR < 60
  FF_API_AUTO_THREADS* = LIBAVCODEC_VERSION_MAJOR < 60
  FF_API_INIT_PACKET* = LIBAVCODEC_VERSION_MAJOR < 60
  FF_API_AVCTX_TIMEBASE* = LIBAVCODEC_VERSION_MAJOR < 60
  FF_API_MPEGVIDEO_OPTS* = LIBAVCODEC_VERSION_MAJOR < 60
  FF_API_FLAG_TRUNCATED* = LIBAVCODEC_VERSION_MAJOR < 60
  FF_API_SUB_TEXT_FORMAT* = LIBAVCODEC_VERSION_MAJOR < 60
