from libavutil_version import AV_VERSION_INT, AV_VERSION

when defined(windows):
  {.push importc, dynlib: "avcodec(|-55|-56|-57|-58|-59).dll", cdecl.}
elif defined(macosx):
  {.push importc, dynlib: "libavcodec(|.55|.56|.57|.58|.59).dylib", cdecl.}
else:
  {.push importc, dynlib: "libavcodec.so(|.55|.56|.57|.58|.59)", cdecl.}

const
  LIBAVCODEC_VERSION_MAJOR* = 58
  LIBAVCODEC_VERSION_MINOR* = 91
  LIBAVCODEC_VERSION_MICRO* = 100
  LIBAVCODEC_VERSION_INT* = AV_VERSION_INT(LIBAVCODEC_VERSION_MAJOR, LIBAVCODEC_VERSION_MINOR, LIBAVCODEC_VERSION_MICRO)
  LIBAVCODEC_VERSION* = AV_VERSION(LIBAVCODEC_VERSION_MAJOR, LIBAVCODEC_VERSION_MINOR, LIBAVCODEC_VERSION_MICRO)
  LIBAVCODEC_BUILD* = LIBAVCODEC_VERSION_INT
  LIBAVCODEC_IDENT* = "Lavc"
  FF_API_LOWRES* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_DEBUG_MV* = LIBAVCODEC_VERSION_MAJOR < 58
  FF_API_AVCTX_TIMEBASE* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_CODED_FRAME* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_SIDEDATA_ONLY_PKT* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_VDPAU_PROFILE* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_CONVERGENCE_DURATION* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_AVPICTURE* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_AVPACKET_OLD_API* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_RTP_CALLBACK* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_VBV_DELAY* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_CODER_TYPE* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_STAT_BITS* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_PRIVATE_OPT* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_ASS_TIMING* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_OLD_BSF* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_COPY_CONTEXT* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_GET_CONTEXT_DEFAULTS* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_NVENC_OLD_NAME* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_STRUCT_VAAPI_CONTEXT* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_MERGE_SD_API* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_TAG_STRING* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_GETCHROMA* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_CODEC_GET_SET* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_USER_VISIBLE_AVHWACCEL* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_LOCKMGR* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_NEXT* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_UNSANITIZED_BITRATES* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_OPENH264_SLICE_MODE* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_OPENH264_CABAC* = LIBAVCODEC_VERSION_MAJOR < 59
  FF_API_UNUSED_CODEC_CAPS* = LIBAVCODEC_VERSION_MAJOR < 59
