from libavutil_version import AV_VERSION_INT, AV_VERSION

when defined(windows):
  {.push importc, dynlib: "avresample(|-0|-1|-2|-3|-4|).dll", cdecl.}
elif defined(macosx):
  {.push importc, dynlib: "avresample(|.0|.1|.2|.3|.4|).dylib", cdecl.}
else:
  {.push importc, dynlib: "libresample.so(|.0|.1|.2|.3|.4|)", cdecl.}

const
  LIBAVRESAMPLE_VERSION_MAJOR* = 4
  LIBAVRESAMPLE_VERSION_MINOR* = 0
  LIBAVRESAMPLE_VERSION_MICRO* = 0
  LIBAVRESAMPLE_VERSION_INT* = AV_VERSION_INT(LIBAVRESAMPLE_VERSION_MAJOR, LIBAVRESAMPLE_VERSION_MINOR, LIBAVRESAMPLE_VERSION_MICRO)
  LIBAVRESAMPLE_VERSION* = AV_VERSION(LIBAVRESAMPLE_VERSION_MAJOR, LIBAVRESAMPLE_VERSION_MINOR, LIBAVRESAMPLE_VERSION_MICRO)
  LIBAVRESAMPLE_BUILD* = LIBAVRESAMPLE_VERSION_INT
  #define LIBAVRESAMPLE_IDENT        "Lavr" AV_STRINGIFY(LIBAVRESAMPLE_VERSION)
