from libavutil_version import AV_VERSION_INT, AV_VERSION

when defined(windows):
  {.push importc, dynlib: "avformat(|-55|-56|-57|-58).dll", cdecl.}
elif defined(macosx):
  {.push importc, dynlib: "libavformat(|.55|.56|.57|.58).dylib", cdecl.}
else:
  {.push importc, dynlib: "libavformat.so(|.55|.56|.57|.58)", cdecl.}

const
  LIBAVFORMAT_VERSION_MAJOR* = 58
  LIBAVFORMAT_VERSION_MINOR* = 45
  LIBAVFORMAT_VERSION_MICRO* = 100
  LIBAVFORMAT_VERSION_INT* = AV_VERSION_INT(LIBAVFORMAT_VERSION_MAJOR, LIBAVFORMAT_VERSION_MINOR, LIBAVFORMAT_VERSION_MICRO)
  LIBAVFORMAT_VERSION* = AV_VERSION(LIBAVFORMAT_VERSION_MAJOR, LIBAVFORMAT_VERSION_MINOR, LIBAVFORMAT_VERSION_MICRO)
  LIBAVFORMAT_BUILD* = LIBAVFORMAT_VERSION_INT
  #define LIBAVFORMAT_IDENT       "Lavf" AV_STRINGIFY(LIBAVFORMAT_VERSION)

when not defined(FF_API_COMPUTE_PKT_FIELDS2):
  const FF_API_COMPUTE_PKT_FIELDS2* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_OLD_OPEN_CALLBACKS):
  const FF_API_OLD_OPEN_CALLBACKS* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_LAVF_AVCTX):
  const FF_API_LAVF_AVCTX* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_HTTP_USER_AGENT):
  const FF_API_HTTP_USER_AGENT* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_HLS_WRAP):
  const FF_API_HLS_WRAP* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_HLS_USE_LOCALTIME):
  const FF_API_HLS_USE_LOCALTIME* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_LAVF_KEEPSIDE_FLAG):
  const FF_API_LAVF_KEEPSIDE_FLAG* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_OLD_ROTATE_API):
  const FF_API_OLD_ROTATE_API* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_FORMAT_GET_SET):
  const FF_API_FORMAT_GET_SET* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_OLD_AVIO_EOF_0):
  const FF_API_OLD_AVIO_EOF_0* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_LAVF_FFSERVER):
  const FF_API_LAVF_FFSERVER* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_FORMAT_FILENAME):
  const FF_API_FORMAT_FILENAME* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_OLD_RTSP_OPTIONS):
  const FF_API_OLD_RTSP_OPTIONS* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_NEXT):
  const FF_API_NEXT* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_DASH_MIN_SEG_DURATION):
  const FF_API_DASH_MIN_SEG_DURATION* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_LAVF_MP4A_LATM):
  const FF_API_LAVF_MP4A_LATM* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_AVIOFORMAT):
  const FF_API_AVIOFORMAT* = LIBAVFORMAT_VERSION_MAJOR < 59

when not defined(FF_API_R_FRAME_RATE):
  const FF_API_R_FRAME_RATE* = 1
