from ../libavutil/version import AV_VERSION_INT, AV_VERSION
from ../libavutil/macros import AV_STRINGIFY

when defined(windows):
  {.push importc, dynlib: "avformat(|-58|-59|-60|-61|-62).dll", cdecl.}
elif defined(macosx):
  {.push importc, dynlib: "libavformat(|.58|.59|.60|.61|.62).dylib", cdecl.}
else:
  {.push importc, dynlib: "libavformat.so(|.58|.59|.60|.61|.62)", cdecl.}

const
  LIBAVFORMAT_VERSION_MAJOR* = 59
  LIBAVFORMAT_VERSION_MINOR* = 16
  LIBAVFORMAT_VERSION_MICRO* = 100
  LIBAVFORMAT_VERSION_INT* = AV_VERSION_INT(LIBAVFORMAT_VERSION_MAJOR, LIBAVFORMAT_VERSION_MINOR, LIBAVFORMAT_VERSION_MICRO)
  LIBAVFORMAT_VERSION* = AV_VERSION(LIBAVFORMAT_VERSION_MAJOR, LIBAVFORMAT_VERSION_MINOR, LIBAVFORMAT_VERSION_MICRO)
  LIBAVFORMAT_BUILD* = LIBAVFORMAT_VERSION_INT
  LIBAVFORMAT_IDENT* = "Lavf" & AV_STRINGIFY(LIBAVFORMAT_VERSION)
  FF_API_LAVF_PRIV_OPT* = LIBAVFORMAT_VERSION_MAJOR < 60
  FF_API_COMPUTE_PKT_FIELDS2* = LIBAVFORMAT_VERSION_MAJOR < 60
  FF_API_AVIOCONTEXT_WRITTEN* = LIBAVFORMAT_VERSION_MAJOR < 60
  FF_HLS_TS_OPTIONS* = LIBAVFORMAT_VERSION_MAJOR < 60
  FF_API_AVSTREAM_CLASS* = LIBAVFORMAT_VERSION_MAJOR > 59
  FF_HTTP_CACHE_REDIRECT_DEFAULT* = LIBAVFORMAT_VERSION_MAJOR < 60
  FF_API_R_FRAME_RATE* = 1
