from ../libavutil/version import AV_VERSION_INT, AV_VERSION
from ../libavutil/macros import AV_STRINGIFY

when defined(windows):
  {.push importc, dynlib: "avfilter(|-7|-8|-9|-10|-11).dll", cdecl.}
elif defined(macosx):
  {.push importc, dynlib: "libavfilter(|.7|.8|.9|.10|.11).dylib", cdecl.}
else:
  {.push importc, dynlib: "avfilter.so(|.7|.8|.9|.10|.11)", cdecl.}

const
  LIBAVFILTER_VERSION_MAJOR* = 8
  LIBAVFILTER_VERSION_MINOR* = 24
  LIBAVFILTER_VERSION_MICRO* = 100
  LIBAVFILTER_VERSION_INT* = AV_VERSION_INT(LIBAVFILTER_VERSION_MAJOR, LIBAVFILTER_VERSION_MINOR, LIBAVFILTER_VERSION_MICRO)
  LIBAVFILTER_VERSION* = AV_VERSION(LIBAVFILTER_VERSION_MAJOR, LIBAVFILTER_VERSION_MINOR, LIBAVFILTER_VERSION_MICRO)
  LIBAVFILTER_BUILD* = LIBAVFILTER_VERSION_INT
  FF_API_SWS_PARAM_OPTION* = LIBAVFILTER_VERSION_MAJOR < 9
  FF_API_BUFFERSINK_ALLOC* = LIBAVFILTER_VERSION_MAJOR < 9
  FF_API_PAD_COUNT* = LIBAVFILTER_VERSION_MAJOR < 9
  LIBAVFILTER_IDENT* = "Lavfi" & AV_STRINGIFY(LIBAVFILTER_VERSION)
