from ../libavutil/version import AV_VERSION_INT, AV_VERSION

when defined(windows):
  {.push importc, dynlib: "avdevice(|-58|-59|-60|-61|-62).dll", cdecl.}
elif defined(macosx):
  {.push importc, dynlib: "libavdevice(|.58|.59|.60|.61|.62).dylib", cdecl.}
else:
  {.push importc, dynlib: "libavdevice.so(|.58|.59|.60|.61|.62)", cdecl.}

const
  LIBAVDEVICE_VERSION_MAJOR* = 59
  LIBAVDEVICE_VERSION_MINOR* = 4
  LIBAVDEVICE_VERSION_MICRO* = 100
  LIBAVDEVICE_VERSION_INT* = AV_VERSION_INT(LIBAVDEVICE_VERSION_MAJOR, LIBAVDEVICE_VERSION_MINOR, LIBAVDEVICE_VERSION_MICRO)
  LIBAVDEVICE_VERSION* = AV_VERSION(LIBAVDEVICE_VERSION_MAJOR, LIBAVDEVICE_VERSION_MINOR, LIBAVDEVICE_VERSION_MICRO)
  LIBAVDEVICE_BUILD* = LIBAVDEVICE_VERSION_INT
  LIBAVDEVICE_IDENT* = "Lavd"
  FF_API_DEVICE_CAPABILITIES* = LIBAVDEVICE_VERSION_MAJOR < 60
